CREATE SCHEMA IF NOT EXISTS billionaires;

CREATE TABLE IF NOT EXISTS billionaires.billionaire
(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  career VARCHAR(250) DEFAULT NULL
);